SELECT COUNT(*) as COUNT
FROM (
    SELECT 
        GENOTYPE MOD 2 as TYPE_1,
        GENOTYPE DIV 2 MOD 2 as TYPE_2,
        GENOTYPE DIV 2 DIV 2 MOD 2 as TYPE_3
    FROM ECOLI_DATA
) AS SUBTBL
WHERE (TYPE_1 = 1 or TYPE_3 = 1) and TYPE_2 = 0
