WITH SUB_TABLE AS (
    SELECT ID, NTILE(4) over (ORDER BY SIZE_OF_COLONY DESC) as TYPE
    FROM ECOLI_DATA
    )
SELECT ID, 
    CASE
        WHEN TYPE = 1 THEN 'CRITICAL'
        WHEN TYPE = 2 THEN 'HIGH'
        WHEN TYPE = 3 THEN 'MEDIUM'
        WHEN TYPE = 4 THEN 'LOW'
        END AS COLONY_NAME
FROM SUB_TABLE
ORDER BY ID ASC
    