

# WITH max_mem AS (
#     SELECT MEMBER_ID
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY COUNT(*) DESC
#     LIMIT 1
# )

# SELECT sub_sub_table.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, 
#        DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM (
#     SELECT max_mem.MEMBER_ID as MEMBER_ID, MEMBER_PROFILE.MEMBER_NAME as MEMBER_NAME
#     FROM max_mem
#     JOIN MEMBER_PROFILE ON max_mem.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
# ) AS sub_sub_table
# JOIN REST_REVIEW ON sub_sub_table.MEMBER_ID = REST_REVIEW.MEMBER_ID
# ORDER BY REST_REVIEW.REVIEW_DATE ASC, REST_REVIEW.REVIEW_TEXT DESC;

WITH max_mem AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, 
       DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM max_mem
JOIN MEMBER_PROFILE ON max_mem.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
JOIN REST_REVIEW ON max_mem.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;
