WITH MAX_SIZE_BY_YEAR AS (
    -- 연도별로 대장균의 가장 큰 크기를 구함
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
)
SELECT
    EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR, 
    (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM 
    ECOLI_DATA e
JOIN 
    MAX_SIZE_BY_YEAR m
ON 
    EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY 
    YEAR ASC, 
    YEAR_DEV ASC;
